# 예외 처리
+ ##### 파이썬은 try, except를 사용해서 예외적으로 오류를 처리할 수 있게 해준다.

> + ##### 오류가 발생하는 대표적인 경우들
> ##### 1. 디렉터리안에 없는 파일을 열려고 시도했을 때
> ```
> >>> f = open("나없는파일",'r')
> Traceback(most recent call last):
>   File "<stdin>", line 1, in <module>
> FileNotfoundError: [Errno 2] No such file or directory: '나없는파일'
> ```
> ##### 없는 파일을 열려고 시도하면 FileNotFoundError 오류가 발생한다.
> &nbsp;
> ##### 2. 0으로 다른 숫자를 나누는 경우
> ```
> >>> 4 / 0
> Traceback ( most rencent call last) :
>   File "<stdin>", line 1, in <module>
> ZeroDivisionError: division by zero
> ```
> ##### 4를 0으로 나누려니까 ZeroDivisionError 오류가 발생한다.
> &nbsp;
> ##### 3. 리스트 안에 없는 값 호출하기
> ```
> >>> a = [1, 2, 3]
> >>> a[4]
> Traceback (most recent call last) : 
>   File "<stdin>", line 1, in <module>
> IndexError: list index out of range
> ```
> ##### a는 리스트 [1,2,3]인데 a[4]는 a리스트에서 얻을 수 없는 값이다. 따라서 IndexError 오류가 발생하였다.
> &nbsp;
> ##### 파이썬은 이런 오류가 발생하면 프로그램을 중단하고 오류 메시지를 보여준다.
&nbsp;
> + ##### 오류 예외 처리 기법
> ##### __try, except 문__ 
> ```
> # 기본 구조
> try:
>     ...
> except [발생오류[as 오류 메시지 변수]]:
>     ...
> ```
> ##### try 블록 수행 중 오류가 발생하면 except 블록이 수행된다. 하지만 try 블록에서 오류가 발생하지 않는다면 except 블록은 수행되지 않는다.
> ##### except 구문을 보면 []기호를 사용하는데, 이기호는 괄 호 안의 내용을 생략할 수 있다는 관례 표현기법이다.
> &nbsp;
> ##### except 구문은 다음 3가지 방법으로 사용할 수 있다.
> ##### 1) try, except만 쓰는 방법
>```
>try:
>    ...
>except:
>    ...
> ```    
> ##### 오류종류에 상관없이 오류가 발생하면 except 블록을 수행한다.
> &nbsp;
> ##### 2) 발생 오류만 포함한 except문
> ```
> try :
>     ...
> except 발생 오류:
>     ...
> ```
> ##### 오류가 발생했을 때 except문에 미리 정해 놓은 오류 이름과 일치할 때만 except블록을 수행
> &nbsp;
> ##### 3) 발생 오류와 오류 메시지 변수까지 포함한 except문
> ```
> try :
>     ...
> except 발생 오류 as 오류 메시지 변수:
>     ...
> ```
> ##### 오류 메시지의 내용까지 알고 싶을 때 사용하는 방법이다.
>  &nbsp;
> ##### __try ... finally__ 
> ##### finally절은 try문 수행 도중 예외 발생 여부에 상관없이 항상 수행된다. 
> ##### 보통 finally 절은 사용한 리소스를 close해야할 때에 많이 사용한다.
> ```python
> f = open('foo.txt', 'w')
> try:
>    # 무언가를 수행한다. 
> finally:
>     f.close()
> ```
> ##### foo.txt파일을 쓰기 모드로 연 후에 try문을 수행한 후 예외 발생 여부와 상관없이 finally 절에서 f.close()로 열린 파일을 닫을 수 있다.
>  &nbsp;
> ##### __여러 개의 오류 처리하기__
> ##### try문 안에서 여러개의 오류를 처리하기 위해 다음 구문을 사용한다.
> ``` python
> try:
>     ...
> except 발생 오류 1:
>     ...
> except 발생 오류 2:
>     ...
> ```
> ##### ex) 0으로 나누는 오류와 인덱싱 오류 처리하기
>  ```python
>  try:
>     a = [1, 2]
>     print(a[3])
>     4/0
> except ZeroDivisonError:
>     print("0으로 나눌 수 없습니다.")
> except indexError:
>     print("인덱싱할 수 없습니다.")
> ```
> ##### a는 2개의 요솟값을 가지고 있기 때문에 a[3]는 IndexError를 발생시키므로 '인덱싱할 수 없습니다.'라는 문자열이 출력될 것이다. 인덱싱 오류가 먼저 발생했으므로 4/0으로 발생되는 ZeroDivisionError오류는 발생하지 않을 것이다.
> &nbsp;
> ##### 오류 메시지도 다음과 같이 가져올 수 있다.
> ```python
> try:
>    a = [1,2]
>    print(a[3])
>    4/0
> except ZeroDivisionError as e:
>    print(e)
> except IndexError as e:
>    print(e)
> ```
> ##### 아래와 같이 ZeroDivisionError와 IndexError를 함께 처리할 수도 있다.
> ```python
> try:
>    a = [1,2]
>    print(a[3])
>    4/0
> except (ZeroDivisionError, IndexError) as e:
>    print(e)
> ```
> ##### 2개 이상의 오류를 동시에 처리하기 위해서는 위와 같이 괄호를 사용하여 함께 묶어 처리하면 된다.
&nbsp;
> + ##### 오류 회피하기
> ##### try문 안에서 FileNotFoundError가 발생할 경우에 pass를 사용하여 오류를 그냥 회피하도록 작성
> ```python
> try:
>    f = open("나없는파일".'r')
> except FileNotFoundError:
>    pass
> ```
&nbsp;
> + ##### 오류 일부러 발생시키기
> ##### raise 명령어를 사용해 오류를 강제로 발생시킬 수 있다.
> ##### ex) Bird 클래스를 상속받는 자식 클래스는 반드시 fly라는 함수를 구현하도록 만들고 싶은 경우
> ```python
> class Bird;
>     def fly(self):
>         raise NotImplementedError
> ```
> ##### 자식 클래스가  fly 함수를 구현하지 않은 상태로 fly 함수 호출하기
> ```python
> class Eagle(Bird):
>     pass
>eagle = Eagle()
>eagle.fly()
>```
>##### Eagle 클래스는 Brid 클래스를 상속받는다. 그런데 Eagle 클래스에서 fly 함수를 구현하지 않았기 때문에 Bird 클래스의  fly 함수가 호출된다. 그리고 raise문에 의해 NotImplemented Error가 발생할 것이다.
>  &nbsp;
> ##### NotImplementedError가 발생되지 않게 하려면 다음과 같이 Eagle 클래스에 fly 함수를 반드시 구현해야한다.
> ```python
> class Eagle(Bird):
>     def fly(self):
>         print("very fast")
>
> eagle = Eagle()
> eagle.fly
>```
> ##### 위 예 처럼 fly 함수를 구현한 후 프로그램을 실행하면 오류 없이 very fast가 출력된다.
&nbsp;
>  + ##### 예외 만들기
> ##### 프로그램 수행 도중 특수한 경우에만 예외 처리를 하기 위해서 종종 예외를 만들어서 사용한다.
> ##### 예외는 파이썬 내장 클래스인 Exception 클래스를 상속하여 만들 수 있다.
> ```python
> class MyError(Exception):
>     pass
> ```
> ##### 예외 만들기 예시)
> ```python 
> def say_nic(nick):
>     if nic == '바보':
>         raise My Error()
>     print(nick)
> 
> try: 
>     say_nick("천사")
>     say_nick("바보")
> except MyError: # 예외 처리 기법을 사용하여 MyError 발생을 예외 처리 하였다.
>     print("허용되지 않는 별명입니다.")
> ```
> &nbsp;
> ##### 오류 메시지를 출력했을 때 오류메시지가 보이게 하려면 오류 클래스에 다음과 같은 __ str__ 메서드를 구현해야한다. __str __ 메서드는 print(e)처럼 오류 메시지를 print문으로 출력할 경우에 호출되는 메서드이다.
> ``` python
> class MyError(Exception):
>     def __str__(self):
>         return "허용되지 않는 별명입니다."
> ```